proj_name: cereal_fungi
home: /home/salias
outdir: /scratch/salias/projects
raw_data: /home/salias/data/cereal_fungi

# Expermient

end: paired
r1_suf: R1
r2_suf: R2
primer_f: TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG GATGAAGAACGYAGYRAA
primer_r: GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG TCCTCCGCTTWTTGWTWTGC
