__default__:
    jobname: default
    time: 1-00:00:00 # time limit for each job
    ncpus: 1
    memory: 2G
    output: logs/default/job_default_%j.out
    error: logs/default/job_default_%j.err

all:
    jobname: all
    time: 0-00:05:00
    ncpus: 1
    memory: 50
    output: logs/all/all_%j.out
    error: logs/all/all_%j.err

fastqc_before:
    jobname: fastqc_before
    time: 0-01:00:00
    ncpus: 2 # one for each FASTQ file, forward and reverse
    memory: 500
    output: logs/fastqc_before/fastqc_before_%j.out
    error: logs/fastqc_before/fastqc_before_%j.err

cutadapt:
    jobname: cutadapt
    time: 0-01:00:00
    ncpus: 2 #cluster# Change cutadapt_n_threads accordingly in config.yml
    memory: 500
    output: logs/cutadapt/cutadapt_%j.out
    error: logs/cutadapt/cutadapt_%j.err

fastqc_after:
    jobname: fastqc_after
    time: 0-01:00:00
    ncpus: 2 # one for each FASTQ file, forward and reverse
    memory: 500
    output: logs/fastqc_after/fastqc_after_%j.out
    error: logs/fastqc_after/fastqc_after_%j.err

multiqc:
    jobname: multiqc
    time: 0-00:10:00
    ncpus: 1
    memory: 500
    output: logs/multiqc/multiqc_%j.out
    error: logs/multiqc/multiqc_%j.err

create_manifest:
    jobname: create_manifest
    time: 0-00:10:00
    ncpus: 1
    memory: 200
    output: logs/create_manifest/create_manifest_%j.out
    error: logs/create_manifest/create_manifest_%j.err

import_fastq:
    jobname: import_fastq
    time: 0-01:00:00
    ncpus: 1
    memory: 4G # Should be more than the FASTQ files total size
    output: logs/import_fastq/import_fastq_%j.out
    error: logs/import_fastq/import_fastq_%j.err

itsxpress:
    jobname: itsxpress
    time: 0-02:00:00
    ncpus: 16 #cluster# Change itsxpress_n_threads accordingly in config.yml
    memory: 4G
    output: logs/itsxpress/itsxpress_%j.out
    error: logs/itsxpress/itsxpress_%j.err

dada2:
    jobname: dada2
    time: 0-02:00:00
    ncpus: 20 #cluster# Change dada2_n_threads accordingly in config.yml
    memory: 25G
    output: logs/dada2/dada2_%j.out
    error: logs/dada2/dada2_%j.err

group_feature_table:
    jobname: group_feature_table
    time: 0-00:10:00
    ncpus: 1
    memory: 2G
    output: logs/group_feature_table/group_feature_table_%j.out
    error: logs/group_feature_table/group_feature_table_%j.err

taxonomy:
    jobname: taxonomy
    time: 0-01:00:00
    ncpus: 2 #cluster# Change sklearn_n_threads accordingly in config.yml
    memory: 75G
    output: logs/taxonomy/taxonomy_%j.out
    error: logs/taxonomy/taxonomy_%j.err

adapt_metadata:
    jobname: adapt_metadata
    time: 0-00:10:00
    ncpus: 1
    memory: 200
    output: logs/adapt_metadata/adapt_metadata_%j.out
    error: logs/adapt_metadata/adapt_metadata_%j.err

plot_feature_table:
    jobname: plot_feature_table
    time: 0-00:15:00
    ncpus: 1
    memory: 500
    output: logs/plot_feature_table/plot_feature_table_%j.out
    error: logs/plot_feature_table/plot_feature_table_%j.err

diversity:
    jobname: diversity
    time: 0-01:00:00
    ncpus: 4 #cluster# Change beta_diversity_n_threads accordingly in config.yml
    memory: 10G
    output: logs/diversity/diversity_%j.out
    error: logs/diversity/diversity_%j.err