########################
# IMPORTANT INFORMATION:
#
# Variables commented with [ #cluster# ] must be
# changed accordingly in cluster_config.yml
########################


### General ###

proj_name: cereal_fungi                                   #-------#    Project name
outdir: /scratch/salias/projects                          #-------#    Directory with all projects
raw_data: /home/salias/data/cereal_fungi                  #-------#    Directory with FASTQ files
metadata: /home/salias/projects/sporeflow/metadata.tsv    #-------#    Metadata file. Modify it with your experiment details (it needs to have metadata.tsv as filename)
type: ITS                                                 #-------#    Region sequenced: 16S (bacteria, not implemented yet) or ITS (fungi)


### Databases ###

db_dir: /home/salias/data/sf_databases/UNITE                 #-------#    Directory where database is stored
db_file: unite_ver10_dynamic_all_04.04.2024-Q2-2024.2.qza    #-------#    Database filename


### Sequences ###

end: paired    #-------#    Options: single or paired (end)
r1_suf: R1     #-------#    Forward read suffix (ignored if end: single)
r2_suf: R2     #-------#    Reverse read suffix (ignored if end: single)


### Cutadapt ###

cutadapt_trim_3_prime: True                #-------#    To trim (True) or not to trim (False) reverse complementary of primers in the 3' end
cutadapt_primer_f: GATGAAGAACGYAGYRAA      #-------#    Forward primer sequence (ignored if trim_primers: False)
cutadapt_primer_r: TCCTCCGCTTWTTGWTWTGC    #-------#    Reverse primer sequence (ignored if trim_primers: False)
cutadapt_n_threads: 2                      #cluster#    Number of threads to use for multithreaded processing


### ITSxpress ###

use_itsxpress: True          #-------#    True if you want to use ITSxpress, False otherwise (the rest of ITSxpress options will be ignored then)
itsxpress_region: ITS2       #-------#    Regions ITS2, ITS1, and ALL can be selected
itsxpress_cluster_id: 1.0    #-------#    Percent identity for clustering reads (0.995-1). Set to 1 for exact dereplication
itsxpress_n_threads: 16      #cluster#    Number of threads to use for multithreaded processing (ITSxpress stops reducing runtime at about 10 cores)


### DADA2 ###

dada2_trim_left_f: 0     #-------#    Position at which forward read sequences should be trimmed due to low quality
dada2_trim_left_r: 0     #-------#    Position at which reverse read sequences should be trimmed due to low quality
dada2_trunc_len_f: 0     #-------#    Position at which forward read sequences should be truncated due to decrease in quality
dada2_trunc_len_r: 0     #-------#    Position at which reverse read sequences should be truncated due to decrease in quality
dada2_max_ee_f: 8        #-------#    Forward reads with number of expected errors higher than this value will be discarded
dada2_max_ee_r: 8        #-------#    Reverse reads with number of expected errors higher than this value will be discarded
dada2_trunc_q: 8         #-------#    Reads are truncated at the first instance of a quality score less than or equal to this value
dada2_min_overlap: 12    #-------#    Minimum length of the overlap required for merging the forward and reverse reads
dada2_n_threads: 20      #cluster#    Number of threads to use for multithreaded processing


### Taxonomic classification ###

taxonomy_n_threads: 2    #cluster#    Maximum number of concurrent worker processes


### Diversity analysis ###

diversity_rarefaction_steps: 20          #-------#    Rarefaction depths to include
diversity_rarefaction_iterations: 10     #-------#    Rarefaction depths to include
diversity_beta_n_threads: 4              #cluster#    Number of concurrent jobs to use in performing beta methods