########################
# IMPORTANT INFORMATION:
#
# Variables commented with [ #cluster# ] must be
# changed accordingly in cluster_config.yml
########################


### General ###

proj_name: cefun_itsxpress                                #-------#    Project name
outdir: /scratch/salias/projects                          #-------#    Directory with all projects
raw_data: /home/salias/data/cereal_fungi                  #-------#    Directory with FASTQ files
metadata: /home/salias/projects/sporeflow/metadata.tsv    #-------#    Metadata file. Modify it with your experiment details (it needs to have metadata.tsv as filename)
type: ITS                                                 #-------#    Region sequenced: 16S (bacteria, not implemented yet) or ITS (fungi)


### Databases ###

db_dir: /home/salias/data/sf_databases/UNITE            #-------#    Directory where database is stored
db_file: unite_ver10_99_all_04.04.2024-Q2-2024.2.qza    #-------#    Database filename


### Sequences ###

end: paired    #-------#    Options: paired (single end not supported for now)
r1_suf: R1     #-------#    Forward read suffix (DO NOT CHANGE)
r2_suf: R2     #-------#    Reverse read suffix (DO NOT CHANGE)


### Cutadapt ###

use_cutadapt: False             #-------#    True if you want to use Cutadapt, False otherwise (the rest of Cutadapt options will be ignored then)
cutadapt_trim_3_prime: True     #-------#    To trim (True) or not to trim (False) reverse complementary of primers in the 3' end
cutadapt_primer_f: ITS3_KYO2    #-------#    Forward primer name present in resources/ITS_primers.tsv or custom sequence
cutadapt_primer_r: ITS4_KYO1    #-------#    Reverse primer name present in resources/ITS_primers.tsv or custom sequence
cutadapt_n_threads: 2           #cluster#    Number of threads to use for multithreaded processing


### ITSxpress ###

use_itsxpress: True          #-------#    True if you want to use ITSxpress, False otherwise (the rest of ITSxpress options will be ignored then)
itsxpress_region: ITS2       #-------#    Regions ITS2, ITS1, and ALL can be selected
itsxpress_cluster_id: 1.0    #-------#    Percent identity for clustering reads (0.995-1). Set to 1 for exact dereplication
itsxpress_n_threads: 16      #cluster#    Number of threads to use for multithreaded processing (ITSxpress stops reducing runtime at about 10 cores)


### DADA2 ###

dada2_trim_left_f: 0     #-------#    Position at which forward read sequences should be trimmed due to low quality
dada2_trim_left_r: 0     #-------#    Position at which reverse read sequences should be trimmed due to low quality
dada2_trunc_len_f: 0     #-------#    Position at which forward read sequences should be truncated due to decrease in quality
dada2_trunc_len_r: 0     #-------#    Position at which reverse read sequences should be truncated due to decrease in quality
dada2_max_ee_f: 2        #-------#    Forward reads with number of expected errors higher than this value will be discarded
dada2_max_ee_r: 2        #-------#    Reverse reads with number of expected errors higher than this value will be discarded
dada2_trunc_q: 2         #-------#    Reads are truncated at the first instance of a quality score less than or equal to this value
dada2_min_overlap: 12    #-------#    Minimum length of the overlap required for merging the forward and reverse reads
dada2_n_threads: 20      #cluster#    Number of threads to use for multithreaded processing


### Taxonomic classification ###

taxonomy_n_threads: 2    #cluster#    Maximum number of concurrent worker processes


### Filter junk ###

kingdom_to_keep: k__Fungi     #-------#    All sequencies not belonging to that kingdom will be discarded. Options available: k__Fungi (note the double underscore '_')
min_taxa_level: c__           #-------#    All sequences without annotations at least as general as this taxonomic level will be discarded.
#-------------------------------------#    Available levels (note the double underscore '_'):
#-------------------------------------#      k__: Kingdom
#-------------------------------------#      p__: Phylum (conservative)
#-------------------------------------#      c__: Class (recommended)
#-------------------------------------#      o__: Order (recommended)
#-------------------------------------#      f__: Family
#-------------------------------------#      g__: Genus
#-------------------------------------#      s__: Species (you will likely discard almost everything)


### Diversity analysis ###

diversity_rarefaction_steps: 20                         #-------#    Rarefaction depths to include
diversity_rarefaction_iterations: 10                    #-------#    Number of rarefied feature tables to compute at each step
diversity_beta_group_significance_method: permanova     #-------#    Group significance test to be applied in beta group significance. Options: permanova, anosim, permdisp
diversity_beta_n_threads: 4                             #cluster#    Number of concurrent jobs to use in performing beta methods


### Differential abundance ###

abundance_collapse_levels: 5;6;7      #-------#    Taxonomic levels to collapse prior to ANCOM-BC.
#---------------------------------------------#    Levels must be separated with semicolons (;) and you must specify at least one level.
#---------------------------------------------#    Available levels:
#---------------------------------------------#      1: Kingdom
#---------------------------------------------#      2: Phylum
#---------------------------------------------#      3: Class
#---------------------------------------------#      4: Order
#---------------------------------------------#      5: Family (recommended)
#---------------------------------------------#      6: Genus (recommended)
#---------------------------------------------#      7: Species (try if you feel confident)
abundance_meta_col: Type              #-------#    Metadata column for differential abundance (and also for beta group significances)
abundance_meta_ref: CON               #-------#    Metadata column reference value
abundance_p_alpha: 0.05               #-------#    Significance level
abundance_barplot_threshold: 0.05     #-------#    To exclude features from the barplot